name: Latest blog posts workflow

on:
  schedule:
  # Runs every hour
  - cron: '0 * * * *'
  # Run this workflow manually when needed
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://medium.com/feed/@danielcapra'
